// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/models/shared"
	"net/http"
)

type DeleteConfigRequest struct {
	// Mapping Config Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteConfigRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The deleted mapping config
	MappingConfig *shared.MappingConfig
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteConfigResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteConfigResponse) GetMappingConfig() *shared.MappingConfig {
	if o == nil {
		return nil
	}
	return o.MappingConfig
}

func (o *DeleteConfigResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteConfigResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
