// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/models/shared"
	"net/http"
)

type GetMappingConfigRequest struct {
	// Mapping Config Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetMappingConfigRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetMappingConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Entity Mapping Config
	MappingConfigV2 *shared.MappingConfigV2
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetMappingConfigResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetMappingConfigResponse) GetMappingConfigV2() *shared.MappingConfigV2 {
	if o == nil {
		return nil
	}
	return o.MappingConfigV2
}

func (o *GetMappingConfigResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetMappingConfigResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
