// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/models/shared"
	"net/http"
)

type PutMappingConfigRequest struct {
	// Mapping Config to store
	MappingConfigV2 *shared.MappingConfigV2 `request:"mediaType=application/json"`
	// Mapping Config Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PutMappingConfigRequest) GetMappingConfigV2() *shared.MappingConfigV2 {
	if o == nil {
		return nil
	}
	return o.MappingConfigV2
}

func (o *PutMappingConfigRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type PutMappingConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The updated entity mapping config
	MappingConfigV2 *shared.MappingConfigV2
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutMappingConfigResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutMappingConfigResponse) GetMappingConfigV2() *shared.MappingConfigV2 {
	if o == nil {
		return nil
	}
	return o.MappingConfigV2
}

func (o *PutMappingConfigResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutMappingConfigResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
