// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/models/shared"
	"net/http"
)

type QueryMappingHistoryRequest struct {
	// filter the history from this date on
	From           *string `queryParam:"style=form,explode=true,name=from"`
	SourceEntityID *string `queryParam:"style=form,explode=true,name=sourceEntityId"`
	TargetEntityID *string `queryParam:"style=form,explode=true,name=targetEntityId"`
	// filter the history to this date on
	To *string `queryParam:"style=form,explode=true,name=to"`
}

func (o *QueryMappingHistoryRequest) GetFrom() *string {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *QueryMappingHistoryRequest) GetSourceEntityID() *string {
	if o == nil {
		return nil
	}
	return o.SourceEntityID
}

func (o *QueryMappingHistoryRequest) GetTargetEntityID() *string {
	if o == nil {
		return nil
	}
	return o.TargetEntityID
}

func (o *QueryMappingHistoryRequest) GetTo() *string {
	if o == nil {
		return nil
	}
	return o.To
}

// QueryMappingHistoryResponseBody - Query result of mapping history
type QueryMappingHistoryResponseBody struct {
	Results []shared.MappingHistoryResp `json:"results,omitempty"`
}

func (o *QueryMappingHistoryResponseBody) GetResults() []shared.MappingHistoryResp {
	if o == nil {
		return nil
	}
	return o.Results
}

type QueryMappingHistoryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Query result of mapping history
	Object *QueryMappingHistoryResponseBody
}

func (o *QueryMappingHistoryResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *QueryMappingHistoryResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *QueryMappingHistoryResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *QueryMappingHistoryResponse) GetObject() *QueryMappingHistoryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
