// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/models/shared"
	"net/http"
)

type StoreConfigRequest struct {
	// Mapping Config to store
	MappingConfig *shared.MappingConfig `request:"mediaType=application/json"`
	// Whether ids are part of the body or not
	WithID *string `queryParam:"style=form,explode=true,name=with_id"`
}

func (o *StoreConfigRequest) GetMappingConfig() *shared.MappingConfig {
	if o == nil {
		return nil
	}
	return o.MappingConfig
}

func (o *StoreConfigRequest) GetWithID() *string {
	if o == nil {
		return nil
	}
	return o.WithID
}

type StoreConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The updated entity mapping config
	MappingConfig *shared.MappingConfig
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *StoreConfigResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *StoreConfigResponse) GetMappingConfig() *shared.MappingConfig {
	if o == nil {
		return nil
	}
	return o.MappingConfig
}

func (o *StoreConfigResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *StoreConfigResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
