// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MappingConfigV2 struct {
	ID      string         `json:"id"`
	Source  SourceConfig   `json:"source"`
	Targets []TargetConfig `json:"targets"`
}

func (o *MappingConfigV2) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *MappingConfigV2) GetSource() SourceConfig {
	if o == nil {
		return SourceConfig{}
	}
	return o.Source
}

func (o *MappingConfigV2) GetTargets() []TargetConfig {
	if o == nil {
		return []TargetConfig{}
	}
	return o.Targets
}
