// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/pkg/utils"
	"time"
)

type MappingConfigV2 struct {
	CreatedAt     *time.Time     `json:"created_at,omitempty"`
	CreatedBy     *Owner         `json:"created_by,omitempty"`
	ID            string         `json:"id"`
	LastUpdatedBy *Owner         `json:"last_updated_by,omitempty"`
	OrgID         *string        `json:"org_id,omitempty"`
	Source        SourceConfig   `json:"source"`
	Targets       []TargetConfig `json:"targets"`
	UpdatedAt     *time.Time     `json:"updated_at,omitempty"`
	Version       *int64         `json:"version,omitempty"`
}

func (m MappingConfigV2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MappingConfigV2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MappingConfigV2) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *MappingConfigV2) GetCreatedBy() *Owner {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *MappingConfigV2) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *MappingConfigV2) GetLastUpdatedBy() *Owner {
	if o == nil {
		return nil
	}
	return o.LastUpdatedBy
}

func (o *MappingConfigV2) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *MappingConfigV2) GetSource() SourceConfig {
	if o == nil {
		return SourceConfig{}
	}
	return o.Source
}

func (o *MappingConfigV2) GetTargets() []TargetConfig {
	if o == nil {
		return []TargetConfig{}
	}
	return o.Targets
}

func (o *MappingConfigV2) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *MappingConfigV2) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}
