// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/pkg/utils"
)

type MappingAttributesType string

const (
	MappingAttributesTypeMappingAttributeV2 MappingAttributesType = "MappingAttributeV2"
	MappingAttributesTypeMappingAttribute   MappingAttributesType = "MappingAttribute"
)

type MappingAttributes struct {
	MappingAttributeV2 *MappingAttributeV2
	MappingAttribute   *MappingAttribute

	Type MappingAttributesType
}

func CreateMappingAttributesMappingAttributeV2(mappingAttributeV2 MappingAttributeV2) MappingAttributes {
	typ := MappingAttributesTypeMappingAttributeV2

	return MappingAttributes{
		MappingAttributeV2: &mappingAttributeV2,
		Type:               typ,
	}
}

func CreateMappingAttributesMappingAttribute(mappingAttribute MappingAttribute) MappingAttributes {
	typ := MappingAttributesTypeMappingAttribute

	return MappingAttributes{
		MappingAttribute: &mappingAttribute,
		Type:             typ,
	}
}

func (u *MappingAttributes) UnmarshalJSON(data []byte) error {

	mappingAttributeV2 := new(MappingAttributeV2)
	if err := utils.UnmarshalJSON(data, &mappingAttributeV2, "", true, true); err == nil {
		u.MappingAttributeV2 = mappingAttributeV2
		u.Type = MappingAttributesTypeMappingAttributeV2
		return nil
	}

	mappingAttribute := new(MappingAttribute)
	if err := utils.UnmarshalJSON(data, &mappingAttribute, "", true, true); err == nil {
		u.MappingAttribute = mappingAttribute
		u.Type = MappingAttributesTypeMappingAttribute
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u MappingAttributes) MarshalJSON() ([]byte, error) {
	if u.MappingAttributeV2 != nil {
		return utils.MarshalJSON(u.MappingAttributeV2, "", true)
	}

	if u.MappingAttribute != nil {
		return utils.MarshalJSON(u.MappingAttribute, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type TargetConfig struct {
	// Pass it as true, when you don't want failures to interrupt the mapping process.
	AllowFailure  *bool       `json:"allow_failure,omitempty"`
	ConditionMode interface{} `json:"conditionMode,omitempty"`
	Conditions    interface{} `json:"conditions,omitempty"`
	// Identifier for target configuration. Useful for later usages when trying to identify which target config to map to.
	ID *string `json:"id,omitempty"`
	// Relation attribute on the main entity where the target entity will be linked. Set to false to disable linkback
	//
	LinkbackRelationAttribute *string `default:"mapped_entities" json:"linkback_relation_attribute"`
	// Relation tags (labels) to include in main entity linkback relation attribute
	LinkbackRelationTags []string `json:"linkback_relation_tags,omitempty"`
	// Attribute mappings
	MappingAttributes []MappingAttributes `json:"mapping_attributes"`
	// A name for this configuration
	Name *string `json:"name,omitempty"`
	// Relation mappings
	RelationAttributes []RelationAttribute `json:"relation_attributes,omitempty"`
	// Schema of target entity
	TargetSchema string `json:"target_schema"`
	// Unique key for target entity (see upsertEntity of Entity API)
	TargetUnique []string `json:"target_unique,omitempty"`
}

func (t TargetConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TargetConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TargetConfig) GetAllowFailure() *bool {
	if o == nil {
		return nil
	}
	return o.AllowFailure
}

func (o *TargetConfig) GetConditionMode() interface{} {
	if o == nil {
		return nil
	}
	return o.ConditionMode
}

func (o *TargetConfig) GetConditions() interface{} {
	if o == nil {
		return nil
	}
	return o.Conditions
}

func (o *TargetConfig) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TargetConfig) GetLinkbackRelationAttribute() *string {
	if o == nil {
		return nil
	}
	return o.LinkbackRelationAttribute
}

func (o *TargetConfig) GetLinkbackRelationTags() []string {
	if o == nil {
		return nil
	}
	return o.LinkbackRelationTags
}

func (o *TargetConfig) GetMappingAttributes() []MappingAttributes {
	if o == nil {
		return []MappingAttributes{}
	}
	return o.MappingAttributes
}

func (o *TargetConfig) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TargetConfig) GetRelationAttributes() []RelationAttribute {
	if o == nil {
		return nil
	}
	return o.RelationAttributes
}

func (o *TargetConfig) GetTargetSchema() string {
	if o == nil {
		return ""
	}
	return o.TargetSchema
}

func (o *TargetConfig) GetTargetUnique() []string {
	if o == nil {
		return nil
	}
	return o.TargetUnique
}
