// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ExecuteMappingReq - Pass either source or source_entity
type ExecuteMappingReq struct {
	SourceRef EntityRef `json:"source_ref"`
	// Mapping Configuration to apply.
	Targets []TargetConfig `json:"targets"`
}

func (o *ExecuteMappingReq) GetSourceRef() EntityRef {
	if o == nil {
		return EntityRef{}
	}
	return o.SourceRef
}

func (o *ExecuteMappingReq) GetTargets() []TargetConfig {
	if o == nil {
		return []TargetConfig{}
	}
	return o.Targets
}
