// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ExecuteRelationsResp struct {
	Relations []NewRelationItem `json:"relations,omitempty"`
}

func (o *ExecuteRelationsResp) GetRelations() []NewRelationItem {
	if o == nil {
		return nil
	}
	return o.Relations
}
