// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type JourneyRef struct {
	JourneyID *string `json:"journey_id,omitempty"`
}

func (o *JourneyRef) GetJourneyID() *string {
	if o == nil {
		return nil
	}
	return o.JourneyID
}
