// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type MappingConfigsResp struct {
	Configs []MappingConfig `json:"configs"`
}

func (o *MappingConfigsResp) GetConfigs() []MappingConfig {
	if o == nil {
		return []MappingConfig{}
	}
	return o.Configs
}
