// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MappingHistoryResp struct {
	Results []MappingHistoryEntry `json:"results"`
}

func (o *MappingHistoryResp) GetResults() []MappingHistoryEntry {
	if o == nil {
		return []MappingHistoryEntry{}
	}
	return o.Results
}
