// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/internal/utils"
)

type Error struct {
	AdditionalProperties any     `additionalProperties:"true" json:"-"`
	IsSilent             *bool   `json:"isSilent,omitempty"`
	Message              *string `json:"message,omitempty"`
}

func (e Error) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Error) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Error) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *Error) GetIsSilent() *bool {
	if o == nil {
		return nil
	}
	return o.IsSilent
}

func (o *Error) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type MappingFailure struct {
	Error  *Error        `json:"error,omitempty"`
	Target *TargetConfig `json:"target,omitempty"`
}

func (o *MappingFailure) GetError() *Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *MappingFailure) GetTarget() *TargetConfig {
	if o == nil {
		return nil
	}
	return o.Target
}
