// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type MappingConfigV2 struct {
	ID      string       `json:"id"`
	Source  SourceConfig `json:"source"`
	Targets any          `json:"targets"`
}

func (o *MappingConfigV2) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *MappingConfigV2) GetSource() SourceConfig {
	if o == nil {
		return SourceConfig{}
	}
	return o.Source
}

func (o *MappingConfigV2) GetTargets() any {
	if o == nil {
		return nil
	}
	return o.Targets
}
