// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Two struct {
	Max  types.Number `tfsdk:"max"`
	Min  types.Number `tfsdk:"min"`
	Type types.String `tfsdk:"type"`
}
