// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type EntityRef struct {
	EntityID     types.String `tfsdk:"entity_id"`
	EntitySchema types.String `tfsdk:"entity_schema"`
}
