// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type Config struct {
	EntityRef  *EntityRef  `tfsdk:"entity_ref"`
	JourneyRef *JourneyRef `tfsdk:"journey_ref"`
}
