// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Owner struct {
	OrgID  types.String `tfsdk:"org_id"`
	Type   types.String `tfsdk:"type"`
	UserID types.String `tfsdk:"user_id"`
}
