// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

type Config struct {
	EntityRef  *EntityRef  `tfsdk:"entity_ref" tfPlanOnly:"true"`
	JourneyRef *JourneyRef `tfsdk:"journey_ref" tfPlanOnly:"true"`
}
