// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyRef struct {
	JourneyID types.String `tfsdk:"journey_id"`
}
