// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type LoopConfig struct {
	Length     types.Number `tfsdk:"length"`
	SourcePath types.String `tfsdk:"source_path"`
}
