// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type MappingAttributes struct {
	Any              types.String      `tfsdk:"any" tfPlanOnly:"true"`
	MappingAttribute *MappingAttribute `tfsdk:"mapping_attribute" tfPlanOnly:"true"`
}
