// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type MappingAttributeV2 struct {
	Operation OperationNode `tfsdk:"operation"`
	Origin    types.String  `tfsdk:"origin"`
	Target    types.String  `tfsdk:"target"`
}
