// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

type MappingAttribute struct {
	AppendValueMapper *AppendValueMapper `tfsdk:"append_value_mapper" tfPlanOnly:"true"`
	CopyValueMapper   *CopyValueMapper   `tfsdk:"copy_value_mapper" tfPlanOnly:"true"`
	SetValueMapper    *SetValueMapper    `tfsdk:"set_value_mapper" tfPlanOnly:"true"`
}
