// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

type MappingAttributes struct {
	MappingAttribute   *MappingAttribute   `tfsdk:"mapping_attribute" tfPlanOnly:"true"`
	MappingAttributeV2 *MappingAttributeV2 `tfsdk:"mapping_attribute_v2" tfPlanOnly:"true"`
}
