// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type OperationNode struct {
	Any                 types.String         `tfsdk:"any" tfPlanOnly:"true"`
	OperationObjectNode *OperationObjectNode `tfsdk:"operation_object_node" tfPlanOnly:"true"`
}
