// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type OperationObjectNode struct {
	Append               []types.String   `tfsdk:"append"`
	Copy                 types.String     `tfsdk:"copy"`
	Random               *RandomOperation `tfsdk:"random"`
	Set                  types.String     `tfsdk:"set"`
	Template             types.String     `tfsdk:"template"`
	Uniq                 *Uniq            `tfsdk:"uniq"`
	AdditionalProperties types.String     `tfsdk:"additional_properties"`
}
