// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

type RandomOperation struct {
	One *One `tfsdk:"one" tfPlanOnly:"true"`
	Two *Two `tfsdk:"two" tfPlanOnly:"true"`
}
