// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type RelationAttribute struct {
	Mode                    types.String   `tfsdk:"mode"`
	Origin                  types.String   `tfsdk:"origin"`
	SourceFilter            *SourceFilter  `tfsdk:"source_filter"`
	Target                  types.String   `tfsdk:"target"`
	TargetTags              []types.String `tfsdk:"target_tags"`
	TargetTagsIncludeSource types.Bool     `tfsdk:"target_tags_include_source"`
}
