// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SetValueMapper struct {
	Mode   types.String `tfsdk:"mode"`
	Target types.String `tfsdk:"target"`
	Value  types.String `tfsdk:"value"`
}
