// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SourceConfig struct {
	Config *Config      `tfsdk:"config"`
	Type   types.String `tfsdk:"type"`
}
