// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Two struct {
	Max  types.Number `tfsdk:"max"`
	Min  types.Number `tfsdk:"min"`
	Type types.String `tfsdk:"type"`
}
