// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/pkg/models/shared"
	"net/http"
)

type ExecuteRelationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The relations which were for both source entity and main entity
	ExecuteRelationsResp *shared.ExecuteRelationsResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ExecuteRelationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ExecuteRelationsResponse) GetExecuteRelationsResp() *shared.ExecuteRelationsResp {
	if o == nil {
		return nil
	}
	return o.ExecuteRelationsResp
}

func (o *ExecuteRelationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ExecuteRelationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
