// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/pkg/models/shared"
	"net/http"
)

type ExecuteMappingRequest struct {
	ExecuteMappingReq *shared.ExecuteMappingReq `request:"mediaType=application/json"`
	// True, if you want to preview the entities which will result
	PreviewMode *bool `queryParam:"style=form,explode=true,name=preview_mode"`
}

func (o *ExecuteMappingRequest) GetExecuteMappingReq() *shared.ExecuteMappingReq {
	if o == nil {
		return nil
	}
	return o.ExecuteMappingReq
}

func (o *ExecuteMappingRequest) GetPreviewMode() *bool {
	if o == nil {
		return nil
	}
	return o.PreviewMode
}

type ExecuteMappingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The target entities which were mapped
	ExecuteMappingResp *shared.ExecuteMappingResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ExecuteMappingResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ExecuteMappingResponse) GetExecuteMappingResp() *shared.ExecuteMappingResp {
	if o == nil {
		return nil
	}
	return o.ExecuteMappingResp
}

func (o *ExecuteMappingResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ExecuteMappingResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
