// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entitymapping/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAllVersionsRequest struct {
	// Mapping Config Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetAllVersionsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetAllVersionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// All versions of a MappingConfig
	MappingConfigsResp *shared.MappingConfigsResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAllVersionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllVersionsResponse) GetMappingConfigsResp() *shared.MappingConfigsResp {
	if o == nil {
		return nil
	}
	return o.MappingConfigsResp
}

func (o *GetAllVersionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllVersionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
